on:
  push:
    branches:
      - deploy-yarn

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Upgrade pip, setuptools, and wheel
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools wheel
    
    - name: Install dependencies
      run: |
        pip install awsebcli --upgrade
    
    - name: Configure AWS credentials
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
    - name: Deploy to Elastic Beanstalk
      run: |
        eb init recommendationservice-node-16 --region us-west-1 --platform Node.js
        eb deploy Recommendationservice-node-16-env 
